-- Test inventory around Camp, Pune.
-- Run this in Supabase Dashboard -> SQL Editor after schema.sql and rls.sql.

insert into public.properties (
  id,
  title,
  locality,
  locality_tag,
  city,
  state,
  bhk,
  rent,
  deposit,
  area,
  type,
  status,
  image_url,
  features,
  description,
  latitude,
  longitude,
  is_active
)
values
  (
    'bp-pune-camp-101',
    'Bright 1 BHK off MG Road',
    'MG Road Camp',
    'Camp',
    'Pune',
    'Maharashtra',
    '1 BHK',
    24000,
    65000,
    610,
    'Apartment',
    'Ready',
    'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80',
    array['Furnished', 'Walkable market', 'Lift'],
    'Compact furnished home close to MG Road and daily essentials.',
    18.5169,
    73.8797,
    true
  ),
  (
    'bp-pune-camp-102',
    'Quiet Studio near East Street',
    'East Street Camp',
    'Camp',
    'Pune',
    'Maharashtra',
    '1 RK',
    18500,
    45000,
    360,
    'Studio',
    'Verified',
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80',
    array['Studio', 'Low maintenance', 'Central location'],
    'Simple studio for one renter who wants a central Pune address.',
    18.5157,
    73.8821,
    true
  ),
  (
    'bp-pune-camp-103',
    'Managed 2 BHK near Clover Center',
    'Clover Center Camp',
    'Camp',
    'Pune',
    'Maharashtra',
    '2 BHK',
    36000,
    90000,
    980,
    'Apartment',
    'Ready',
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80',
    array['Family friendly', 'Balcony', 'Security'],
    'A practical two-bedroom home near Camp shopping and offices.',
    18.5182,
    73.8769,
    true
  ),
  (
    'bp-pune-camp-104',
    'Budget Room near Pune Station',
    'Pune Station Road',
    'Camp',
    'Pune',
    'Maharashtra',
    '1 RK',
    14500,
    30000,
    280,
    'Room',
    'Budget',
    'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1000&q=80',
    array['Low deposit', 'Transit access', 'Shared kitchen'],
    'Budget room with quick access to Pune Station and Camp.',
    18.5271,
    73.8743,
    true
  ),
  (
    'bp-pune-camp-105',
    'Airy 1 BHK in Rasta Peth',
    'Rasta Peth',
    'Camp',
    'Pune',
    'Maharashtra',
    '1 BHK',
    22000,
    55000,
    575,
    'Apartment',
    'Ready',
    'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1000&q=80',
    array['Ventilated', 'Market nearby', 'Bike parking'],
    'Light-filled 1 BHK in a central lane close to Camp and Peth areas.',
    18.5178,
    73.8648,
    true
  ),
  (
    'bp-pune-camp-106',
    'Premium 2 BHK near Koregaon Park',
    'Bund Garden Road',
    'Camp',
    'Pune',
    'Maharashtra',
    '2 BHK',
    42000,
    110000,
    1050,
    'Apartment',
    'Verified',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80',
    array['Gated society', 'Covered parking', 'Lift'],
    'Well-kept 2 BHK between Camp, Bund Garden, and Koregaon Park.',
    18.5334,
    73.8795,
    true
  ),
  (
    'bp-pune-camp-107',
    'Compact 1 BHK near Wanowrie',
    'Wanowrie Road',
    'Camp',
    'Pune',
    'Maharashtra',
    '1 BHK',
    20500,
    50000,
    540,
    'Apartment',
    'Ready',
    'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1000&q=80',
    array['No brokerage', 'Bus stop nearby', 'Semi furnished'],
    'A compact home south of Camp with simple commute options.',
    18.4932,
    73.8997,
    true
  ),
  (
    'bp-pune-camp-108',
    'Spacious 2 BHK near Swargate',
    'Shankar Sheth Road',
    'Camp',
    'Pune',
    'Maharashtra',
    '2 BHK',
    33000,
    85000,
    920,
    'Apartment',
    'Hot',
    'https://images.unsplash.com/photo-1560448075-bb485b067938?auto=format&fit=crop&w=1000&q=80',
    array['Spacious', 'Transit access', 'Family friendly'],
    'Roomy 2 BHK with strong access to Swargate and Camp.',
    18.5018,
    73.8642,
    true
  )
on conflict (id) do update
set
  title = excluded.title,
  locality = excluded.locality,
  locality_tag = excluded.locality_tag,
  city = excluded.city,
  state = excluded.state,
  bhk = excluded.bhk,
  rent = excluded.rent,
  deposit = excluded.deposit,
  area = excluded.area,
  type = excluded.type,
  status = excluded.status,
  image_url = excluded.image_url,
  features = excluded.features,
  description = excluded.description,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  is_active = excluded.is_active,
  updated_at = now();

delete from public.property_images
where property_id like 'bp-pune-camp-%';

insert into public.property_images (property_id, image_url, alt_text, sort_order)
select id, image_url, 'Cover', 0
from public.properties
where id like 'bp-pune-camp-%';
